//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenPracticoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomicilioCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DomicilioCliente()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int DomicilioClienteId { get; set; }
        public int ClienteId { get; set; }
        public string Calle { get; set; }
        public int NumeroExterior { get; set; }
        public Nullable<int> NumeroInterior { get; set; }
        public string Colonia { get; set; }
        public int CodigoPostal { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string EmailPrincipal { get; set; }
        public string EmailSecundario { get; set; }
        public decimal TotalCompra { get; set; }
        public Nullable<int> ContadorCompras { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
