//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenPracticoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaDetalle
    {
        public int VentaDetalleId { get; set; }
        public int VentaId { get; set; }
        public string ProductoCodigo { get; set; }
        public string ProductoDescripcion { get; set; }
        public decimal ProductoPrecioUnitario { get; set; }
        public int ProductoCantidad { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}
