//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenPracticoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int VentaId { get; set; }
        public int ClienteId { get; set; }
        public int DomicilioClienteId { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal Subtotal { get; set; }
        public int TotalArticulos { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual DomicilioCliente DomicilioCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
